jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2  # This checks out the repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub PAT from GitHub Secrets

    - name: Build the Docker image
      run: |
        sudo docker build -t static-website .

    - name: Run the Docker container
      run: |
        sudo docker run -d -p 8080:80 static-website  # Run the container on port 8080

    - name: Push the Docker image to Docker Hub
      run: docker push static-website  # Push the image to Docker Hub

